// <auto-generated />
using System;
using ABC.PostGreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ABC.PostGreSQL.Migrations
{
    [DbContext(typeof(ABCContext))]
    [Migration("20260530202125_AddEntityTranslationsAndLanguage")]
    partial class AddEntityTranslationsAndLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ABC.Management.Domain.Entities.Antecedent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_antecedents");

                    b.ToTable("antecedents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6c5ca3b-6ade-4b65-b0e3-64af93caee49"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "A sudden or unexpected loud sound in the environment",
                            Name = "Loud noise",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30b66d14-a9e3-4037-8ec1-1f05bc7ec940"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "A request or demand was denied or refused",
                            Name = "Denied request",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("948150ee-a06f-46e2-a76a-9955ddaeb809"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Transitioning between activities or locations",
                            Name = "Transition",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("45815eee-87b7-4123-9ebc-2b06913d3309"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "A task or instruction was presented",
                            Name = "Task demand",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3ddfccd6-0a2b-485b-9333-b2e13aad51f8"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Peer or adult social engagement initiated",
                            Name = "Social interaction",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0a44ef8e-8d7a-45af-9d0b-c243db8bcfd6"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Child was left without attention or interaction",
                            Name = "Left alone",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bdaceb17-3b6d-430b-ba49-9ea2024da58d"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "A disruption or change to the expected schedule",
                            Name = "Change in routine",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ec3398d0-622b-4dbe-ba95-5f46f6c647b6"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Exposure to a specific sensory input (light, texture, smell)",
                            Name = "Sensory stimulus",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4d9a81b5-4473-43e6-936b-e1be563cec21"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "A preferred item or activity was taken away",
                            Name = "Preferred item removed",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4ffdd6e3-f8a9-4731-adb2-dee92e675288"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Required to wait for a turn, item, or activity",
                            Name = "Waiting",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2cf3462-ce01-493a-9355-93a072be45af"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Disagreement or conflict with a peer",
                            Name = "Peer conflict",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b22744f0-206b-45aa-85b7-f53624bd1c86"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Physical state of hunger, thirst, or tiredness",
                            Name = "Hunger or fatigue",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ABC.Management.Domain.Entities.Behavior", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_behaviors");

                    b.ToTable("behaviors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c25168ef-7ef7-4a8b-9c1d-351e89df4e20"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Crying or tearfulness",
                            Name = "Crying",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6d51409e-bbdc-45dc-a50f-8404c6681047"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Hitting others with hands or objects",
                            Name = "Hitting",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("36404391-9bc1-4fea-879e-c33647ac0adc"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Kicking others or objects",
                            Name = "Kicking",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b15aef26-7008-4fe5-9448-4c72da6c1e15"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Screaming or yelling loudly",
                            Name = "Screaming",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8db0289d-0a4f-4ff6-9e80-b2d718771c9e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Biting self or others",
                            Name = "Biting",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("fe85c34d-c5eb-4a59-be23-47b464198b2a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Throwing items or materials",
                            Name = "Throwing objects",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e18be934-2d56-423b-9cc9-f5516d08ecb0"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Leaving the designated area without permission",
                            Name = "Elopement",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("82f3efe1-97c3-404e-a0ca-66d240a446cd"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Refusing to follow instructions or directions",
                            Name = "Noncompliance",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9af0cc72-dd3b-4784-9173-90df515c5b1e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Engaging in self-injurious behavior (head-banging, scratching)",
                            Name = "Self-injury",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4c1ef311-cace-4d45-b7b1-147b28f88d91"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Extended episode of crying, screaming, and physical resistance",
                            Name = "Tantrums",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8f44e0f6-0d10-44bc-8c52-6c34ffb1b39e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Breaking, tearing, or damaging items",
                            Name = "Property destruction",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("eef83b9c-7852-49cd-8bc5-b99c22128334"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Using threatening or hostile language",
                            Name = "Verbal aggression",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ABC.Management.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birthYear");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdBy");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("pK_children");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_children_userId");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("ABC.Management.Domain.Entities.ChildCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_childConditions");

                    b.ToTable("childConditions", (string)null);
                });

            modelBuilder.Entity("ABC.Management.Domain.Entities.Consequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_consequences");

                    b.ToTable("consequences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("441cd995-f81e-4950-99cd-c8ffeb88358a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Redirected to a different activity or task",
                            Name = "Redirected",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7d6054ce-0670-4eee-896a-759f79553074"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Received a verbal correction or reprimand",
                            Name = "Verbal reprimand",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aedf4064-7aeb-4e24-b690-795d9e1b7692"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Behavior was intentionally ignored (planned ignoring)",
                            Name = "Ignored",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d8ba54d1-7417-47bc-9646-3b99090105b0"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Received attention (verbal, physical, or proximity)",
                            Name = "Given attention",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4cfc6a22-e070-410c-b029-dba6129af02d"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "The demand or task was removed or postponed",
                            Name = "Task removed",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("90c0e8f6-508a-479a-be5f-9d6a9e41c0e2"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Given access to a preferred item or activity",
                            Name = "Access to preferred item",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e7d2dfa7-daec-4e26-a509-3cef2ff08f0f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Removed from the reinforcing environment temporarily",
                            Name = "Time-out",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4575b00c-6938-4b5d-964b-666fc865fd89"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Received physical guidance to complete a task",
                            Name = "Physical prompt",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9de37eeb-5008-4fdb-b123-3cbd563b5c57"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Peers reacted to the behavior (laughing, crying, moving away)",
                            Name = "Peer reaction",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("537642d3-0608-44ae-a89a-5028ddceeb59"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "A natural consequence occurred without adult intervention",
                            Name = "Natural consequence",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ABC.Management.Domain.Entities.EntityTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entityId");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entityType");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_entityTranslations");

                    b.HasIndex("EntityType", "EntityId", "Language")
                        .IsUnique()
                        .HasDatabaseName("iX_entityTranslations_entityType_entityId_language");

                    b.ToTable("entityTranslations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Un sonido fuerte repentino o inesperado en el entorno",
                            EntityId = new Guid("a6c5ca3b-6ade-4b65-b0e3-64af93caee49"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Ruido fuerte",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Una solicitud o demanda fue denegada o rechazada",
                            EntityId = new Guid("30b66d14-a9e3-4037-8ec1-1f05bc7ec940"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Solicitud denegada",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Transición entre actividades o lugares",
                            EntityId = new Guid("948150ee-a06f-46e2-a76a-9955ddaeb809"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Transición",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Se presentó una tarea o instrucción",
                            EntityId = new Guid("45815eee-87b7-4123-9ebc-2b06913d3309"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Demanda de tarea",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Se inició una interacción social con un compañero o adulto",
                            EntityId = new Guid("3ddfccd6-0a2b-485b-9333-b2e13aad51f8"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Interacción social",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "El niño fue dejado sin atención o interacción",
                            EntityId = new Guid("0a44ef8e-8d7a-45af-9d0b-c243db8bcfd6"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Dejado solo",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Una interrupción o cambio en el horario esperado",
                            EntityId = new Guid("bdaceb17-3b6d-430b-ba49-9ea2024da58d"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Cambio en la rutina",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Exposición a un estímulo sensorial específico (luz, textura, olor)",
                            EntityId = new Guid("ec3398d0-622b-4dbe-ba95-5f46f6c647b6"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Estímulo sensorial",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Un objeto o actividad preferida fue retirado",
                            EntityId = new Guid("4d9a81b5-4473-43e6-936b-e1be563cec21"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Objeto preferido retirado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Se requirió esperar un turno, objeto o actividad",
                            EntityId = new Guid("4ffdd6e3-f8a9-4731-adb2-dee92e675288"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Espera",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Desacuerdo o conflicto con un compañero",
                            EntityId = new Guid("b2cf3462-ce01-493a-9355-93a072be45af"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Conflicto con compañeros",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Estado físico de hambre, sed o cansancio",
                            EntityId = new Guid("b22744f0-206b-45aa-85b7-f53624bd1c86"),
                            EntityType = 1,
                            Language = "es",
                            Name = "Hambre o fatiga",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Llanto o lagrimeo",
                            EntityId = new Guid("c25168ef-7ef7-4a8b-9c1d-351e89df4e20"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Llanto",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Golpear a otros con las manos u objetos",
                            EntityId = new Guid("6d51409e-bbdc-45dc-a50f-8404c6681047"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Golpear",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Patear a otros u objetos",
                            EntityId = new Guid("36404391-9bc1-4fea-879e-c33647ac0adc"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Patear",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Gritar o vociferar fuertemente",
                            EntityId = new Guid("b15aef26-7008-4fe5-9448-4c72da6c1e15"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Gritar",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Morderse a sí mismo o a otros",
                            EntityId = new Guid("8db0289d-0a4f-4ff6-9e80-b2d718771c9e"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Morder",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Lanzar artículos o materiales",
                            EntityId = new Guid("fe85c34d-c5eb-4a59-be23-47b464198b2a"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Lanzar objetos",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Abandonar el área designada sin permiso",
                            EntityId = new Guid("e18be934-2d56-423b-9cc9-f5516d08ecb0"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Fuga",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Negarse a seguir instrucciones o direcciones",
                            EntityId = new Guid("82f3efe1-97c3-404e-a0ca-66d240a446cd"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Incumplimiento",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Participar en comportamiento autolesivo (golpearse la cabeza, rascarse)",
                            EntityId = new Guid("9af0cc72-dd3b-4784-9173-90df515c5b1e"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Autolesión",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Episodio prolongado de llanto, gritos y resistencia física",
                            EntityId = new Guid("4c1ef311-cace-4d45-b7b1-147b28f88d91"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Berrinches",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Romper, rasgar o dañar artículos",
                            EntityId = new Guid("8f44e0f6-0d10-44bc-8c52-6c34ffb1b39e"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Destrucción de propiedad",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Usar lenguaje amenazante u hostil",
                            EntityId = new Guid("eef83b9c-7852-49cd-8bc5-b99c22128334"),
                            EntityType = 2,
                            Language = "es",
                            Name = "Agresión verbal",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Redirigido a una actividad o tarea diferente",
                            EntityId = new Guid("441cd995-f81e-4950-99cd-c8ffeb88358a"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Redirigido",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Recibió una corrección o reprimenda verbal",
                            EntityId = new Guid("7d6054ce-0670-4eee-896a-759f79553074"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Reprimenda verbal",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "El comportamiento fue ignorado intencionalmente (ignorar planificado)",
                            EntityId = new Guid("aedf4064-7aeb-4e24-b690-795d9e1b7692"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Ignorado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Recibió atención (verbal, física o de proximidad)",
                            EntityId = new Guid("d8ba54d1-7417-47bc-9646-3b99090105b0"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Atención recibida",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "La demanda o tarea fue eliminada o pospuesta",
                            EntityId = new Guid("4cfc6a22-e070-410c-b029-dba6129af02d"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Tarea eliminada",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Se le dio acceso a un objeto o actividad preferida",
                            EntityId = new Guid("90c0e8f6-508a-479a-be5f-9d6a9e41c0e2"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Acceso a objeto preferido",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Retirado del entorno reforzante temporalmente",
                            EntityId = new Guid("e7d2dfa7-daec-4e26-a509-3cef2ff08f0f"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Tiempo fuera",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Recibió guía física para completar una tarea",
                            EntityId = new Guid("4575b00c-6938-4b5d-964b-666fc865fd89"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Indicación física",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Los compañeros reaccionaron al comportamiento (riendo, llorando, alejándose)",
                            EntityId = new Guid("9de37eeb-5008-4fdb-b123-3cbd563b5c57"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Reacción de compañeros",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Ocurrió una consecuencia natural sin intervención de un adulto",
                            EntityId = new Guid("537642d3-0608-44ae-a89a-5028ddceeb59"),
                            EntityType = 3,
                            Language = "es",
                            Name = "Consecuencia natural",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ABC.Management.Domain.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("childId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdBy");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pK_observations");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("iX_observations_childId");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("ABC.PostGreSQL.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencyStamp");

                    b.Property<Guid?>("DefaultChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("defaultChildId");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailConfirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedEmail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedUserName");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("passwordHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phoneNumberConfirmed");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferredLanguage");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("securityStamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("twoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("userName");

                    b.HasKey("Id")
                        .HasName("pK_AspNetUsers");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AntecedentObservation", b =>
                {
                    b.Property<Guid>("AntecedentsId")
                        .HasColumnType("uuid")
                        .HasColumnName("antecedentsId");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid")
                        .HasColumnName("observationsId");

                    b.HasKey("AntecedentsId", "ObservationsId")
                        .HasName("pK_antecedentObservation");

                    b.HasIndex("ObservationsId")
                        .HasDatabaseName("iX_antecedentObservation_observationsId");

                    b.ToTable("antecedentObservation", (string)null);
                });

            modelBuilder.Entity("BehaviorObservation", b =>
                {
                    b.Property<Guid>("BehaviorsId")
                        .HasColumnType("uuid")
                        .HasColumnName("behaviorsId");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid")
                        .HasColumnName("observationsId");

                    b.HasKey("BehaviorsId", "ObservationsId")
                        .HasName("pK_behaviorObservation");

                    b.HasIndex("ObservationsId")
                        .HasDatabaseName("iX_behaviorObservation_observationsId");

                    b.ToTable("behaviorObservation", (string)null);
                });

            modelBuilder.Entity("ChildChildCondition", b =>
                {
                    b.Property<Guid>("ConditionsId")
                        .HasColumnType("uuid")
                        .HasColumnName("conditionsId");

                    b.Property<Guid>("childrenId")
                        .HasColumnType("uuid")
                        .HasColumnName("childrenId");

                    b.HasKey("ConditionsId", "childrenId")
                        .HasName("pK_childChildCondition");

                    b.HasIndex("childrenId")
                        .HasDatabaseName("iX_childChildCondition_childrenId");

                    b.ToTable("childChildCondition", (string)null);
                });

            modelBuilder.Entity("ConsequenceObservation", b =>
                {
                    b.Property<Guid>("ConsequencesId")
                        .HasColumnType("uuid")
                        .HasColumnName("consequencesId");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid")
                        .HasColumnName("observationsId");

                    b.HasKey("ConsequencesId", "ObservationsId")
                        .HasName("pK_consequenceObservation");

                    b.HasIndex("ObservationsId")
                        .HasDatabaseName("iX_consequenceObservation_observationsId");

                    b.ToTable("consequenceObservation", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencyStamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedName");

                    b.HasKey("Id")
                        .HasName("pK_AspNetRoles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimType");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimValue");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roleId");

                    b.HasKey("Id")
                        .HasName("pK_AspNetRoleClaims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("iX_AspNetRoleClaims_roleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimType");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimValue");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("pK_AspNetUserClaims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_AspNetUserClaims_userId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginProvider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("providerKey");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("providerDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pK_AspNetUserLogins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_AspNetUserLogins_userId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("roleId");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pK_AspNetUserRoles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("iX_AspNetUserRoles_roleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginProvider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pK_AspNetUserTokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ABC.Management.Domain.Entities.Observation", b =>
                {
                    b.HasOne("ABC.Management.Domain.Entities.Child", "Child")
                        .WithMany("Observations")
                        .HasForeignKey("ChildId")
                        .HasConstraintName("fK_observations_children_childId");

                    b.OwnsOne("ABC.Management.Domain.ValueObjects.DateTimeRange", "When", b1 =>
                        {
                            b1.Property<Guid>("ObservationId");

                            b1.Property<DateTime?>("EndedAt");

                            b1.Property<DateTime>("StartedAt");

                            b1.HasKey("ObservationId");

                            b1.ToTable("observations");

                            b1
                                .ToJson("when")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ObservationId")
                                .HasConstraintName("fK_observations_observations_id");
                        });

                    b.OwnsOne("ABC.SharedKernel.DailyContext", "DailyContext", b1 =>
                        {
                            b1.Property<Guid>("ObservationId");

                            b1.Property<bool>("HadBreakfast");

                            b1.Property<bool>("HadDinner");

                            b1.Property<bool>("HadLunch");

                            b1.Property<bool>("HadSnack");

                            b1.Property<int?>("HoursOfSleep");

                            b1.Property<bool>("SleptWell");

                            b1.HasKey("ObservationId");

                            b1.ToTable("observations");

                            b1
                                .ToJson("dailyContext")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ObservationId")
                                .HasConstraintName("fK_observations_observations_id");
                        });

                    b.Navigation("Child");

                    b.Navigation("DailyContext");

                    b.Navigation("When")
                        .IsRequired();
                });

            modelBuilder.Entity("AntecedentObservation", b =>
                {
                    b.HasOne("ABC.Management.Domain.Entities.Antecedent", null)
                        .WithMany()
                        .HasForeignKey("AntecedentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_antecedentObservation_antecedents_antecedentsId");

                    b.HasOne("ABC.Management.Domain.Entities.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_antecedentObservation_observations_observationsId");
                });

            modelBuilder.Entity("BehaviorObservation", b =>
                {
                    b.HasOne("ABC.Management.Domain.Entities.Behavior", null)
                        .WithMany()
                        .HasForeignKey("BehaviorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_behaviorObservation_behaviors_behaviorsId");

                    b.HasOne("ABC.Management.Domain.Entities.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_behaviorObservation_observations_observationsId");
                });

            modelBuilder.Entity("ChildChildCondition", b =>
                {
                    b.HasOne("ABC.Management.Domain.Entities.ChildCondition", null)
                        .WithMany()
                        .HasForeignKey("ConditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_childChildCondition_childConditions_conditionsId");

                    b.HasOne("ABC.Management.Domain.Entities.Child", null)
                        .WithMany()
                        .HasForeignKey("childrenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_childChildCondition_children_childrenId");
                });

            modelBuilder.Entity("ConsequenceObservation", b =>
                {
                    b.HasOne("ABC.Management.Domain.Entities.Consequence", null)
                        .WithMany()
                        .HasForeignKey("ConsequencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_consequenceObservation_consequences_consequencesId");

                    b.HasOne("ABC.Management.Domain.Entities.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_consequenceObservation_observations_observationsId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_AspNetRoleClaims_AspNetRoles_roleId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ABC.PostGreSQL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_AspNetUserClaims_AspNetUsers_userId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ABC.PostGreSQL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_AspNetUserLogins_AspNetUsers_userId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_AspNetUserRoles_AspNetRoles_roleId");

                    b.HasOne("ABC.PostGreSQL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_AspNetUserRoles_AspNetUsers_userId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ABC.PostGreSQL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_AspNetUserTokens_AspNetUsers_userId");
                });

            modelBuilder.Entity("ABC.Management.Domain.Entities.Child", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
